# Generated by Django 3.2.20 on 2023-08-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230831_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='content',
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='slug',
        ),
        migrations.AddField(
            model_name='adoption',
            name='age',
            field=models.IntegerField(default=0, verbose_name='What age Fox Terrier, are you looking for?'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='experience',
            field=models.CharField(default='', max_length=200, verbose_name='What experience with dogs do you have?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='notes',
            field=models.CharField(default='', max_length=200, verbose_name='dditional notes or feedback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='sex',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], default=1, max_length=10, verbose_name='would prefer a Male or Female?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='terrier_type',
            field=models.CharField(choices=[(0, 'Wired'), (1, 'Smooth')], default=1, max_length=10, verbose_name='Which Fox terrier do you want to adopt?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='why',
            field=models.CharField(default='', max_length=200, verbose_name='Why would you like to adopt a Fox Terrier?'),
            preserve_default=False,
        ),
    ]
