# Generated by Django 3.2.20 on 2023-09-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230831_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='age',
            field=models.CharField(default=0, max_length=200, verbose_name='What age Fox Terrier, are you looking for?'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='notes',
            field=models.CharField(max_length=200, verbose_name='Additional notes or feedback'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='would prefer a Male or Female?'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='terrier_type',
            field=models.CharField(choices=[('Wired', 'Wired'), ('Smooth', 'Smooth')], max_length=10, verbose_name='Which Fox terrier do you want to adopt?'),
        ),
    ]
