# Generated by Django 3.2.20 on 2023-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230901_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100, verbose_name='Your Email Address'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Your Name?'),
        ),
    ]
