# Generated by Django 3.2.20 on 2023-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230901_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='name',
            field=models.CharField(default='example: Dave Smith', max_length=100, verbose_name='Your Name?'),
        ),
    ]
