# Generated by Django 3.2.20 on 2023-09-01 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_adoption_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehome',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rehome',
            name='slug',
        ),
        migrations.AddField(
            model_name='rehome',
            name='age',
            field=models.CharField(default=0, max_length=200, verbose_name='What age Fox Terrier, are you looking for?'),
        ),
        migrations.AddField(
            model_name='rehome',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rehome_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehome',
            name='behaviour',
            field=models.CharField(default='your text here', max_length=200, verbose_name='What are they like around other dogs?'),
        ),
        migrations.AddField(
            model_name='rehome',
            name='notes',
            field=models.CharField(default='your text here', max_length=200, verbose_name='Additional notes or feedback'),
        ),
        migrations.AddField(
            model_name='rehome',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='would prefer a Male or Female?'),
        ),
        migrations.AddField(
            model_name='rehome',
            name='terrier_type',
            field=models.CharField(blank=True, choices=[('Wired', 'Wired'), ('Smooth', 'Smooth')], max_length=10, null=True, verbose_name='Which Fox terrier do you want to rehome?'),
        ),
        migrations.AddField(
            model_name='rehome',
            name='why',
            field=models.CharField(default='your text here', max_length=200, verbose_name='Why would you like to rehome a Fox Terrier?'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rehome',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100, verbose_name='Your Email Address'),
        ),
        migrations.AlterField(
            model_name='rehome',
            name='name',
            field=models.CharField(default='example: Dave Smith', max_length=100, verbose_name='Your Name?'),
        ),
    ]
