# Generated by Django 3.2.20 on 2023-09-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230901_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehome',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What age Fox Terrier, are you looking for?'),
        ),
        migrations.AlterField(
            model_name='rehome',
            name='behaviour',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What are they like around other dogs?'),
        ),
        migrations.AlterField(
            model_name='rehome',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Your Name?'),
        ),
        migrations.AlterField(
            model_name='rehome',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional notes or feedback'),
        ),
        migrations.AlterField(
            model_name='rehome',
            name='why',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Why would you like to rehome a Fox Terrier?'),
        ),
    ]
