# Generated by Django 3.2.20 on 2023-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230901_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Your Email Address'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Your Name?'),
        ),
    ]
