# Generated by Django 3.2.20 on 2023-09-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230905_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What age Fox Terrier, are you looking for?'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What experience with dogs do you have?'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional notes or feedback'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='would prefer a Male or Female?'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='terrier_type',
            field=models.CharField(blank=True, choices=[('Wired', 'Wired'), ('Smooth', 'Smooth')], max_length=10, null=True, verbose_name='Which Fox terrier do you want to adopt?'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='why',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Why would you like to adopt a Fox Terrier?'),
        ),
    ]
