# Generated by Django 3.2.20 on 2023-10-23 09:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='adoption_type',
            field=models.CharField(choices=[('Adoption', 'Adoption'), ('Rehome', 'Rehome')], default='Adoption', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='age',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='email',
            field=models.EmailField(default='x@x.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='experience',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='name',
            field=models.CharField(default='m', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='notes',
            field=models.CharField(default='f', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='terrier_type',
            field=models.CharField(choices=[('Wired', 'Wired'), ('Smooth', 'Smooth')], default='Wired', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='why',
            field=models.CharField(default='w', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='Rehome',
        ),
    ]
